# test cases expected data
HtmlMinify: <!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Document</title></head><body><p>Hello, Fiber!</p><input type="hidden" disabled><br></body></html>
html_with_css_default: |-
  <!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Document</title><style>
      /* This a comment */
      body {
        font-family: sans-serif;
        font-size: 16px;
        color: #333333;
        /*
        Sets the background color to white
        and the text color to dark gray
        */
        background-color: #ffffff;
      }
    </style></head><body><p>Hello, Fiber!</p></body></html>
html_with_js_default: |-
  <!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Document</title><script>
      // This is a comment
      alert('Hello, Fiber!')
    </script></head><body><p>Hello, Fiber!</p></body></html>
html_with_css_and_js: |-
  <!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Document</title><style>
      /* This a css comment */
      body {
        font-family: sans-serif;
        font-size: 16px;
        color: #333333;
        /*
        Sets the background color to white
        and the text color to dark gray
        */
        background-color: #ffffff;
      }
    </style></head><body><p>Hello, Fiber!</p><script>
      // This is a js comment
      alert('Hello, Fiber!')
    </script></body></html>
html_config_options_styles_false: |-
  <!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Document</title><style>
      /* This a css comment */
      body {
        font-family: sans-serif;
        font-size: 16px;
        color: #333333;
        /*
        Sets the background color to white
        and the text color to dark gray
        */
        background-color: #ffffff;
      }
    </style></head><body><p>Hello, Fiber!</p><script>alert('Hello, Fiber!')</script></body></html>
html_config_options_js_false: |-
  <!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Document</title><style>body{font-family:sans-serif;font-size:16px;color:#333;background-color:#fff}</style></head><body><p>Hello, Fiber!</p><script>
      // This is a js comment
      alert('Hello, Fiber!')
    </script></body></html>
html_config_options_css_js_false: |-
  <!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Document</title><style>
      /* This a css comment */
      body {
        font-family: sans-serif;
        font-size: 16px;
        color: #333333;
        /*
        Sets the background color to white
        and the text color to dark gray
        */
        background-color: #ffffff;
      }
    </style></head><body><p>Hello, Fiber!</p><script>
      // This is a js comment
      alert('Hello, Fiber!')
    </script></body></html>
html_config_options_css_js_true: <!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Document</title><style>body{font-family:sans-serif;font-size:16px;color:#333;background-color:#fff}</style></head><body><p>Hello, Fiber!</p><script>alert('Hello, Fiber!')</script></body></html>
css_minify: body{font-family:Arial,sans-serif;font-size:16px;line-height:1.5;color:#333;background-color:#fff}h1{font-size:32px;margin-bottom:10px}@media only screen and (max-width:768px){body{font-size:14px;line-height:1.3}h1{font-size:24px;margin-bottom:5px}}@media only screen and (max-width:480px){body{font-size:12px;line-height:1.2}h1{font-size:20px;margin-bottom:5px}}
js_minify: var x=10;function factorial(n){if(n<=1){return 1;};return n*factorial(n-1);};var double=function(x){return x*2;};var numbers=[1,2,3,4,5];for(var i=0;i<numbers.length;i++){numbers[i]=double(numbers[i]);};var person={name:"John",age:30,greet:function(){console.log("Hello, my name is "+this.name+" and I'm "+this.age+" years old.");}};person.greet();